// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually — run 'pnpm -F @clawbot/agent generate:models' to update.
// Hand corrections belong in src/llm/model-overrides.ts.

import type { GeneratedModelCatalog } from "./model-catalog-types.js";

import ANTHROPIC_MODELS from "./data/anthropic.json" with { type: "json" };
import DEEPSEEK_MODELS from "./data/deepseek.json" with { type: "json" };
import GOOGLE_MODELS from "./data/google.json" with { type: "json" };
import GROQ_MODELS from "./data/groq.json" with { type: "json" };
import KIMI_MODELS from "./data/kimi.json" with { type: "json" };
import KIMI_CODING_MODELS from "./data/kimi-coding.json" with { type: "json" };
import MISTRAL_MODELS from "./data/mistral.json" with { type: "json" };
import MOONSHOT_MODELS from "./data/moonshot.json" with { type: "json" };
import OPENAI_MODELS from "./data/openai.json" with { type: "json" };
import OPENROUTER_MODELS from "./data/openrouter.json" with { type: "json" };
import XAI_MODELS from "./data/xai.json" with { type: "json" };
import XIAOMI_MODELS from "./data/xiaomi.json" with { type: "json" };
import XIAOMI_ANTHROPIC_MODELS from "./data/xiaomi-anthropic.json" with { type: "json" };

export const GENERATED_MODEL_CATALOG: GeneratedModelCatalog = {
  "anthropic": ANTHROPIC_MODELS,
  "deepseek": DEEPSEEK_MODELS,
  "google": GOOGLE_MODELS,
  "groq": GROQ_MODELS,
  "kimi": KIMI_MODELS,
  "kimi-coding": KIMI_CODING_MODELS,
  "mistral": MISTRAL_MODELS,
  "moonshot": MOONSHOT_MODELS,
  "openai": OPENAI_MODELS,
  "openrouter": OPENROUTER_MODELS,
  "xai": XAI_MODELS,
  "xiaomi": XIAOMI_MODELS,
  "xiaomi-anthropic": XIAOMI_ANTHROPIC_MODELS,
};
