// oxlint-disable-next-line typescript-eslint/triple-slash-reference
/// <reference path="../hugeicons.d.ts" />

import Activity03Icon from "@hugeicons/core-free-icons/Activity03Icon";
import Add01Icon from "@hugeicons/core-free-icons/Add01Icon";
import HugeAlertCircleIcon from "@hugeicons/core-free-icons/AlertCircleIcon";
import ArrowRight02Icon from "@hugeicons/core-free-icons/ArrowRight02Icon";
import HugeBoltIcon from "@hugeicons/core-free-icons/BoltIcon";
import HugeBookIcon from "@hugeicons/core-free-icons/BookOpen01Icon";
import BubbleChatIcon from "@hugeicons/core-free-icons/BubbleChatIcon";
import Calendar03Icon from "@hugeicons/core-free-icons/Calendar03Icon";
import Cancel01Icon from "@hugeicons/core-free-icons/Cancel01Icon";
import HugeCheckIcon from "@hugeicons/core-free-icons/CheckIcon";
import CheckmarkCircle01Icon from "@hugeicons/core-free-icons/CheckmarkCircle01Icon";
import HugeChevronDownIcon from "@hugeicons/core-free-icons/ChevronDownIcon";
import HugeChevronLeftIcon from "@hugeicons/core-free-icons/ChevronLeftIcon";
import HugeChevronRightIcon from "@hugeicons/core-free-icons/ChevronRightIcon";
import HugeChevronUpIcon from "@hugeicons/core-free-icons/ChevronUpIcon";
import Clock01Icon from "@hugeicons/core-free-icons/Clock01Icon";
import Copy01Icon from "@hugeicons/core-free-icons/Copy01Icon";
import HugeCpuIcon from "@hugeicons/core-free-icons/CpuIcon";
import Delete02Icon from "@hugeicons/core-free-icons/Delete02Icon";
import Diamond01Icon from "@hugeicons/core-free-icons/Diamond01Icon";
import HugeGaugeIcon from "@hugeicons/core-free-icons/GaugeIcon";
import HugeGridIcon from "@hugeicons/core-free-icons/GridIcon";
import HugeHeartIcon from "@hugeicons/core-free-icons/HeartIcon";
import HugeHistoryIcon from "@hugeicons/core-free-icons/HistoryIcon";
import HugeHomeIcon from "@hugeicons/core-free-icons/Home01Icon";
import Key01Icon from "@hugeicons/core-free-icons/Key01Icon";
import Layers01Icon from "@hugeicons/core-free-icons/Layers01Icon";
import Link01Icon from "@hugeicons/core-free-icons/Link01Icon";
import HugeLockIcon from "@hugeicons/core-free-icons/LockIcon";
import Logout01Icon from "@hugeicons/core-free-icons/Logout01Icon";
import HugeMoreHorizontalIcon from "@hugeicons/core-free-icons/MoreHorizontalIcon";
import NeuralNetworkIcon from "@hugeicons/core-free-icons/NeuralNetworkIcon";
import HugePauseIcon from "@hugeicons/core-free-icons/PauseIcon";
import PencilEdit01Icon from "@hugeicons/core-free-icons/PencilEdit01Icon";
import HugePlayIcon from "@hugeicons/core-free-icons/PlayIcon";
import HugePulseIcon from "@hugeicons/core-free-icons/Pulse01Icon";
import HugePuzzleIcon from "@hugeicons/core-free-icons/PuzzleIcon";
import Queue01Icon from "@hugeicons/core-free-icons/Queue01Icon";
import HugeRefreshIcon from "@hugeicons/core-free-icons/RefreshIcon";
import HugeRssIcon from "@hugeicons/core-free-icons/RssIcon";
import HugeScanIcon from "@hugeicons/core-free-icons/ScanIcon";
import Search01Icon from "@hugeicons/core-free-icons/Search01Icon";
import ServerStack01Icon from "@hugeicons/core-free-icons/ServerStack01Icon";
import Settings01Icon from "@hugeicons/core-free-icons/Settings01Icon";
import SlidersHorizontalIcon from "@hugeicons/core-free-icons/SlidersHorizontalIcon";
import HugeTerminalIcon from "@hugeicons/core-free-icons/TerminalIcon";
import Upload01Icon from "@hugeicons/core-free-icons/Upload01Icon";
import HugeWebhookIcon from "@hugeicons/core-free-icons/WebhookIcon";
import Robot02Icon from "@hugeicons/core-free-icons/Robot02Icon";
import { createIcon } from "./create-icon.js";

export type { IconProps } from "./create-icon.js";

export const ActivityIcon = createIcon(Activity03Icon, "ActivityIcon");
export const PulseIcon = createIcon(HugePulseIcon, "PulseIcon");
export const ArrowRightIcon = createIcon(ArrowRight02Icon, "ArrowRightIcon");
export const BoltIcon = createIcon(HugeBoltIcon, "BoltIcon");
export const BookIcon = createIcon(HugeBookIcon, "BookIcon");
export const ChatIcon = createIcon(BubbleChatIcon, "ChatIcon");
export const GridIcon = createIcon(HugeGridIcon, "GridIcon");
export const HomeIcon = createIcon(HugeHomeIcon, "HomeIcon");
export const LinkIcon = createIcon(Link01Icon, "LinkIcon");
export const RssIcon = createIcon(HugeRssIcon, "RssIcon");
export const QueueIcon = createIcon(Queue01Icon, "QueueIcon");
export const PuzzleIcon = createIcon(HugePuzzleIcon, "PuzzleIcon");
export const ScanIcon = createIcon(HugeScanIcon, "ScanIcon");
export const PencilIcon = createIcon(PencilEdit01Icon, "PencilIcon");
export const CheckIcon = createIcon(HugeCheckIcon, "CheckIcon");
export const XIcon = createIcon(Cancel01Icon, "XIcon");
export const SearchIcon = createIcon(Search01Icon, "SearchIcon");
export const StackIcon = createIcon(ServerStack01Icon, "StackIcon");
export const TerminalIcon = createIcon(HugeTerminalIcon, "TerminalIcon");
export const LogOutIcon = createIcon(Logout01Icon, "LogOutIcon");
export const WebhookIcon = createIcon(HugeWebhookIcon, "WebhookIcon");
export const RobotIcon = createIcon(Robot02Icon, "RobotIcon");
export const CopyIcon = createIcon(Copy01Icon, "CopyIcon");
export const TrashIcon = createIcon(Delete02Icon, "TrashIcon");
export const RefreshIcon = createIcon(HugeRefreshIcon, "RefreshIcon");
export const PlusIcon = createIcon(Add01Icon, "PlusIcon");
export const UploadIcon = createIcon(Upload01Icon, "UploadIcon");
export const KeyIcon = createIcon(Key01Icon, "KeyIcon");
export const LockIcon = createIcon(HugeLockIcon, "LockIcon");
export const ClockIcon = createIcon(Clock01Icon, "ClockIcon");
export const ChevronDownIcon = createIcon(HugeChevronDownIcon, "ChevronDownIcon");
export const ChevronLeftIcon = createIcon(HugeChevronLeftIcon, "ChevronLeftIcon");
export const ChevronRightIcon = createIcon(HugeChevronRightIcon, "ChevronRightIcon");
export const ChevronUpIcon = createIcon(HugeChevronUpIcon, "ChevronUpIcon");
export const MoreHorizontalIcon = createIcon(HugeMoreHorizontalIcon, "MoreHorizontalIcon");
export const HistoryIcon = createIcon(HugeHistoryIcon, "HistoryIcon");
export const AlertCircleIcon = createIcon(HugeAlertCircleIcon, "AlertCircleIcon");
export const CheckCircleIcon = createIcon(CheckmarkCircle01Icon, "CheckCircleIcon");
export const PlayIcon = createIcon(HugePlayIcon, "PlayIcon");
export const PauseIcon = createIcon(HugePauseIcon, "PauseIcon");
export const CalendarIcon = createIcon(Calendar03Icon, "CalendarIcon");
export const CpuIcon = createIcon(HugeCpuIcon, "CpuIcon");
export const LayersIcon = createIcon(Layers01Icon, "LayersIcon");
export const SlidersIcon = createIcon(SlidersHorizontalIcon, "SlidersIcon");
export const GaugeIcon = createIcon(HugeGaugeIcon, "GaugeIcon");
export const HeartIcon = createIcon(HugeHeartIcon, "HeartIcon");
export const NetworkIcon = createIcon(NeuralNetworkIcon, "NetworkIcon");
export const DiamondIcon = createIcon(Diamond01Icon, "DiamondIcon");
export const SettingsIcon = createIcon(Settings01Icon, "SettingsIcon");
